#!/usr/bin/bash

NAME=$(basename "$0")

usage() {
	cat << EOF

USAGE: 	$NAME [OPTION]

OPTIONS:
  -h, --help	Display this message
  -s, --server	Enable Hydrus Network server
  -c, --client	Open Hydrus Network client
  -k, --kill	Kills Hydrus Network server processes
  -g, --github	Open Hydrus Network github.io page in browser
  -8, --8ch	Open Hydrus Network 8ch board in browser
EOF
}

hydrus_server() {
	if [[ $(pidof /home/john/Research/hydrusnetwork/server) ]]; then
		echo "Hydrus Network server is already running!"
		echo -n "Would you like to restart the process? [y/n]: "
		read input 
		case $input in
			y|Y)
				hydrus_kill
				hydrus_server
				;;
			n|N)
				echo "Okie dokie"
				;;
			*)
				echo "That wasn't an option!"
		esac
	else
		~/Research/hydrusnetwork/server &
	fi
}

hydrus_client() {
	~/Research/hydrusnetwork/client
}

hydrus_kill() {
	kill -9 $(pidof /home/john/Research/hydrusnetwork/server)
}

hydrus_github() {
	$BROWSER https://hydrusnetwork.github.io/hydrus/
}

hydrus_8ch() {
	$BROWSER https://8ch.net/hydrus/index.html
}

# Catch command line options
case $1 in
	-h|--help)
		usage
		;;
	-s|--server)
		hydrus_server
		;;
	-c|--client)
		hydrus_client
		;;
	-k|--kill)
		hydrus_kill
		;;
	-g|--github)
		hydrus_github
		;;
	-8|--8ch)
		hydrus_8ch
		;;
	*)
		echo -e "Option does not exist: $1" && usage && exit 1
esac
