#!/bin/bash

change() {
	notify-send -t 700 "Volume $(pamixer --get-volume)"
}

mute() {
	MUTED=$(pamixer --get-mute)
	if [[ "$MUTED" == "true" ]]; then
		notify-send -t 700 "Mute"
	elif [[ "$MUTED" == "false" ]]; then
		notify-send -t 700 "Unmute"
	fi
}

case $1 in
	change)
		change	
		;;
	mute)
		mute
		;;
esac
