#!/bin/bash

systemctl --user start feh-randombg.service
systemctl --user start feh-randombg.timer
systemctl --user start check-battery.service
systemctl --user start check-battery.timer
killall picom
picom -bCG --no-fading-openclose --experimental-backends --backend glx
pkill dunst
dunst -config ~/.config/dunst/dunstrc &
